name: dart_plugin_isolate
description: An example Dart project implementing a simple plugin architecture, which dynamically loads plugins in the VM and executes them in an isolate seen through a plugin proxy. The method call serialization is all done automatically with some noSuchMethod() magic.

#  args:
#    sdk: args
#  meta:
#    sdk: meta